#### Второе практическое задание по курсу <<Вычислительная математика>>
*Работа выполнена Твердовым Константином, группа 592.*

Решается **Задача 2**:
>Написать программу для решения произвольной линейной системы с положительно определенной матрицей методом Якоби.

* *Построение положительно определенной матрицы:*
    
    Для любой вещественной обратимой матрицы $A$, произведение $A^TA$ есть положительно определенная матрица, т.к. $x^T(A^TA)x = (Ax)^T(Ax) > 0$ $\forall x \in \mathbb R^n$ и $Ax \neq 0$ ($A$ - невырождена).
    
    Положительная определенность полученной матрицы проверяется по собственным числам.


* Пусть задана СЛАУ $Ax = b$, где $A$ - матрица размера $n \times n$, $b$ $-$ столбец коэффициентов, $x$ $-$ искомый вектор. 

    Согласно методу Якоби представим $A$ в виде $A = D + R$, где $D$ $-$ диагональная матрица.
    
    Тогда $Dx + Rx = b$ и $x = -D^{-1}Rx + D^{-1}b$,
    
    Итерационный метод Якоби строится по формуле $x^{(k+1)} = D^{-1}(-Rx^{(k)} + b)$,

    Используемая далее покомпонентная запись:

    $ x^{(k+1)}_i = \frac{1}{a_{ii}} (-\sum_{i \neq j} a_{ij}x^{(k)}_j + b_i)$.

In [8]:
import numpy as np

In [9]:
def GenPositiveDefiniteMatrix(n):
    A = np.random.random(size=(n,n))
    A = np.dot(A.transpose(), A)
    return A
    
def GenDependentVariables(n):
    return np.random.random(size=n)

In [10]:
def IsMatrixPositiveDefinite(A):
    return np.all(np.linalg.eigvals(A) > 0)

def Norm(x):
    norm_l1 = 0
    
    for i in range(len(x)):
        norm_l1 += np.fabs(x[i])
        
    return norm_l1

In [11]:
def JacobiMethod(a, b, accuracy, x_start=None):
    if (x_start is None):
        x = np.zeros_like(b)
        x_prev = np.zeros_like(b)
    else:
        x = x_start
        x_prev = x_start
    
    n = len(x)
    iters = 0
    
    while Norm(np.dot(A, x) - b) > accuracy:
        
        for i in range(n):
            composition = 0
            
            for j in range(n):
                if j != i:
                    composition += A[i][j] * x_prev[j]
                    
            x[i] = (b[i] - composition) / A[i][i]
        
        x_prev = x
        iters += 1
        
    return x, iters

In [19]:
n = 5
accuracy = 1e-5

A = GenPositiveDefiniteMatrix(n)
print(A, end='\n\n')

b = GenDependentVariables(n)
print(b, end='\n\n')

print(np.linalg.eigvals(A), end='\n\n')

x_linalg = np.linalg.solve(A, b)
print("A linalg solution: ", x_linalg, end='\n\n')

x_jacobi, iters = JacobiMethod(A, b, accuracy)
print("An iterative solution obtained in ",  iters, " iterations: ", x_jacobi, end='\n\n')
print("The exact error: ", Norm(x_jacobi - x_linalg))

[[ 1.84045512  1.38644888  1.45096617  0.99566609  0.92220514]
 [ 1.38644888  1.29455431  0.99192479  0.92184414  0.70456093]
 [ 1.45096617  0.99192479  1.34462255  0.58915295  0.67156302]
 [ 0.99566609  0.92184414  0.58915295  0.8401802   0.6874337 ]
 [ 0.92220514  0.70456093  0.67156302  0.6874337   1.21474897]]

[ 0.59180339  0.79530494  0.05124276  0.48497809  0.95915855]

[ 5.21649121  0.02114442  0.07818534  0.73574992  0.48299026]

A linalg solution:  [ 5.66152051  3.48691159 -6.6089529  -7.05353437  2.11442797]

An iterative solution obtained in  321  iterations:  [ 5.66145935  3.48688346 -6.60889258 -7.05346492  2.11441807]

The exact error:  0.00022895889202


In [13]:
'''
def MatrixNorm(A):
    norm = 0
    
    for i in range(A.shape[0]):
        temp = 0
        for j in range(A.shape[1]):
            temp += A[i][j]
        if (temp > norm):
            norm = temp
            
    return norm
    
D = np.diag(np.diag(A))
R = A - D
B = np.dot(np.linalg.inv(D), R)
print(B)
q = MatrixNorm(B)
print(q)
print("Estimation of error: ", q * Norm(x_linalg))

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-13-547fd41d9656>, line 20)